name: Flutter CI

on:
  push:
    branches: [ master ]
    paths:
      - 'fpfa_app/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'fpfa_app/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true
          
      - name: Install dependencies
        run: flutter pub get
        working-directory: fpfa_app

      - name: Verify formatting
        run: flutter format --set-exit-if-changed .
        working-directory: fpfa_app
        continue-on-error: true

      - name: Analyze project
        run: flutter analyze
        working-directory: fpfa_app

      - name: Run tests
        run: flutter test
        working-directory: fpfa_app
